
---

  - name: Stopping Apache server
    service:
      name: httpd
      state: stopped

  - name: Renewing the certificate
    shell: certbot renew

  - name: Starting Apache server
    service:
      name: httpd
      state: started



